// Prepend // @ts-nocheck to shadcn components (idempotent).
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
// adjust the glob if your shadcn path differs
const DIR = path.join(ROOT, "src/components/ui");

function prependOnce(file, header) {
  const src = fs.readFileSync(file, "utf8");
  if (src.startsWith(header)) return false;
  fs.writeFileSync(file, header + src, "utf8");
  return true;
}

// only top-level files in /ui (not subdirs). change to **/*.tsx if you want all.
const files = fs.readdirSync(DIR)
  .filter(f => f.endsWith(".tsx"))
  .map(f => path.join(DIR, f));

const HEADER =
  "// @ts-nocheck\n" +
  "// NOTE: Generated by shadcn. Local edits may be overwritten.\n";

let changed = 0;
for (const f of files) {
  changed += prependOnce(f, HEADER) ? 1 : 0;
}
console.log(`shadcn-nocheck: updated ${changed} file(s).`);
